
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 16;
  public static final int CONST = 10;
  public static final int CHAR = 9;
  public static final int CASE = 8;
  public static final int SEMI = 35;
  public static final int REPEAT = 23;
  public static final int INT = 18;
  public static final int ARRAY = 5;
  public static final int FOR = 15;
  public static final int WRITE = 32;
  public static final int COMMA = 34;
  public static final int BEGIN = 6;
  public static final int UNTIL = 29;
  public static final int IF = 17;
  public static final int OF = 20;
  public static final int EOF = 0;
  public static final int BOOLEAN = 7;
  public static final int EQUAL = 33;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int PROGRAM = 4;
  public static final int LITERAL = 2;
  public static final int SHORTINT = 24;
  public static final int ELSE = 12;
  public static final int READ = 22;
  public static final int TO = 27;
  public static final int WHILE = 31;
  public static final int THEN = 26;
  public static final int END = 13;
  public static final int STRING = 25;
  public static final int FALSE = 14;
  public static final int LONGINT = 19;
  public static final int VAR = 30;
  public static final int PROCEDURE = 21;
  public static final int DO = 11;
  public static final int IDENTIFIER = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LITERAL",
  "IDENTIFIER",
  "PROGRAM",
  "ARRAY",
  "BEGIN",
  "BOOLEAN",
  "CASE",
  "CHAR",
  "CONST",
  "DO",
  "ELSE",
  "END",
  "FALSE",
  "FOR",
  "FUNCTION",
  "IF",
  "INT",
  "LONGINT",
  "OF",
  "PROCEDURE",
  "READ",
  "REPEAT",
  "SHORTINT",
  "STRING",
  "THEN",
  "TO",
  "TRUE",
  "UNTIL",
  "VAR",
  "WHILE",
  "WRITE",
  "EQUAL",
  "COMMA",
  "SEMI"
  };
}

