/* The following code was generated by JFlex 1.6.1 */

 /* Secci�n de declaraciones de JFlex */
package scanner;
import java_cup.runtime.*;
import parser.sym;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/SegundoSemestre2018/Compiladores e Interpretes/Proyectos/Proyecto2/Parser_ABC/Parser_ABC/src/scanner/ScannerABC.flex</tt>
 */
public class ScannerABC implements java_cup.runtime.Scanner{

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\1\0\10\0\1\4\1\2\1\7\1\7\1\3\22\0\1\1\1\62"+
    "\1\70\1\63\1\62\1\62\1\62\1\0\1\35\1\40\1\36\1\61"+
    "\1\56\1\13\1\11\1\42\1\10\1\6\10\6\1\60\1\56\1\25"+
    "\1\23\1\24\1\0\1\62\1\14\1\26\1\30\1\16\1\12\1\45"+
    "\1\50\1\54\1\47\1\5\1\32\1\27\1\33\1\15\1\17\1\51"+
    "\1\5\1\20\1\53\1\21\1\5\1\55\1\44\1\22\1\43\1\5"+
    "\1\56\1\0\1\57\1\62\1\5\1\0\1\14\1\26\1\30\1\16"+
    "\1\34\1\45\1\50\1\54\1\47\1\5\1\32\1\27\1\33\1\15"+
    "\1\17\1\51\1\5\1\20\1\53\1\21\1\5\1\55\1\44\1\22"+
    "\1\43\1\5\1\41\1\4\1\37\7\0\1\7\33\0\1\67\30\0"+
    "\1\65\4\0\1\65\2\0\1\64\1\66\36\0\1\64\1\66\114\0"+
    "\2\46\115\0\1\52\u1ea8\0\1\7\1\7\u0100\0\1\31\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\1\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\7\4\3\11\2\4\1\12\1\10\1\13\1\14"+
    "\1\10\2\4\1\2\3\4\1\2\1\4\2\7\1\10"+
    "\1\15\3\2\1\16\1\4\1\15\2\0\1\17\1\20"+
    "\4\0\1\20\1\10\2\4\1\0\2\4\1\0\1\11"+
    "\2\4\1\7\3\4\1\0\1\14\1\0\1\17\1\21"+
    "\1\0\2\4\1\0\1\4\4\22\2\4\1\0\1\4"+
    "\1\10\4\15\2\0\1\23\2\16\1\24\1\25\1\0"+
    "\6\4\1\0\5\14\1\0\1\17\1\0\2\4\2\0"+
    "\3\4\1\15\1\16\1\26\1\25\1\17\1\0\1\25"+
    "\3\4\1\0\1\14\1\0\1\17\1\4\1\0\1\4"+
    "\1\0\1\4\1\15\1\0\1\27\1\4\1\0\1\4"+
    "\1\0\1\17\1\14\1\0\1\17\1\0\1\15\2\27"+
    "\1\0\1\17\1\0\1\4\2\0\2\14\1\0\1\17"+
    "\1\15\2\0\1\27\1\0\1\4\1\0\1\17\2\14"+
    "\1\0\1\17\1\15\1\0\2\27\1\0\1\4\1\0"+
    "\2\14\1\0\1\17\1\15\2\0\1\4\1\14\3\0"+
    "\1\4\3\0\1\4\3\0\1\4\1\17\2\0\1\20"+
    "\3\0\1\11";

  private static int [] zzUnpackAction() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\71\0\253\0\344\0\u011d\0\u0156"+
    "\0\u018f\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5\0\u031e"+
    "\0\u0357\0\71\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad"+
    "\0\u04e6\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c\0\u0675"+
    "\0\u06ae\0\u06e7\0\u0720\0\71\0\u0759\0\u0792\0\u07cb\0\u0804"+
    "\0\u083d\0\u0876\0\u08af\0\u08e8\0\u0921\0\u095a\0\u0993\0\u09cc"+
    "\0\u0a05\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\71\0\u0b5b"+
    "\0\u0b94\0\u0bcd\0\u0c06\0\u0c3f\0\u0c78\0\344\0\u0cb1\0\u0cea"+
    "\0\u0d23\0\u0d5c\0\u0d95\0\u0dce\0\u0e07\0\u0e40\0\u0e79\0\u0eb2"+
    "\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\u1041\0\71"+
    "\0\u107a\0\344\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u1197\0\u11d0"+
    "\0\u1209\0\u1242\0\u127b\0\u12b4\0\u12ed\0\u1326\0\u135f\0\u1398"+
    "\0\u0a3e\0\u13d1\0\u140a\0\u1443\0\u147c\0\u14b5\0\u14ee\0\u1527"+
    "\0\u1560\0\u1599\0\u15d2\0\u160b\0\u1644\0\u167d\0\u16b6\0\u16ef"+
    "\0\u1728\0\u1761\0\u179a\0\u17d3\0\u180c\0\u1845\0\u187e\0\u18b7"+
    "\0\u18f0\0\u1929\0\u1962\0\u0a3e\0\u199b\0\u19d4\0\u1a0d\0\u1a0d"+
    "\0\u1a46\0\u1a7f\0\u1ab8\0\u1af1\0\u1b2a\0\u1b63\0\u1b9c\0\u1bd5"+
    "\0\u1c0e\0\u1c47\0\u1c80\0\u1cb9\0\u1cf2\0\u1d2b\0\u1d64\0\u1d9d"+
    "\0\u1dd6\0\u1e0f\0\u1e48\0\u1e81\0\u1eba\0\u1ef3\0\u1f2c\0\u1f65"+
    "\0\u1f9e\0\u1fd7\0\u2010\0\u2049\0\u2082\0\u20bb\0\u20f4\0\u212d"+
    "\0\u2166\0\u219f\0\u21d8\0\u2211\0\u224a\0\u2283\0\u22bc\0\u22f5"+
    "\0\u232e\0\u2367\0\u23a0\0\u23d9\0\u2412\0\u244b\0\u2484\0\u24bd"+
    "\0\u24f6\0\u252f\0\u2568\0\u25a1\0\u25da\0\u2613\0\u264c\0\u2685"+
    "\0\u26be\0\u26f7\0\u2730\0\u2769\0\u27a2\0\u27db\0\u2814\0\u284d"+
    "\0\u2886\0\u28bf\0\u28f8\0\u2931\0\u296a\0\u29a3\0\u29dc\0\u2a15"+
    "\0\u2a4e\0\u2a87\0\u2ac0\0\u2af9\0\u2b32\0\71\0\u2b6b\0\u2ba4"+
    "\0\71\0\u2bdd\0\u2c16\0\u2c4f\0\u2c16";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\3\1\6\1\7\1\0"+
    "\1\10\1\11\1\6\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\6\1\2\3\6\1\27\1\30\1\2\1\31\1\32"+
    "\1\33\1\6\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\2\6\2\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\2\1\52\1\2\1\53\72\0\1\3\2\0"+
    "\1\3\66\0\1\4\73\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\6\1\0\7\6\3\0\3\6\1\0\3\6"+
    "\6\0\3\6\1\0\3\6\1\0\3\6\4\0\1\55"+
    "\1\0\1\56\1\0\1\57\7\0\1\60\1\7\1\0"+
    "\1\7\1\61\1\60\1\0\7\60\3\0\3\60\1\0"+
    "\3\60\2\62\1\0\1\62\2\0\3\60\1\0\3\60"+
    "\1\0\3\60\4\0\2\62\1\63\1\0\1\64\1\0"+
    "\1\65\5\0\1\60\1\10\1\0\1\10\1\61\1\60"+
    "\1\0\7\60\3\0\3\60\1\0\3\60\2\62\1\0"+
    "\1\62\2\0\3\60\1\0\3\60\1\0\3\60\4\0"+
    "\2\62\1\63\1\0\1\64\1\0\1\65\6\0\1\66"+
    "\1\0\1\66\73\0\1\67\7\0\1\67\52\0\1\6"+
    "\1\54\1\0\1\54\1\0\1\6\1\0\1\6\1\70"+
    "\5\6\3\0\3\6\1\0\3\6\6\0\3\6\1\0"+
    "\3\6\1\0\3\6\4\0\1\55\1\0\1\56\1\0"+
    "\1\57\7\0\1\6\1\54\1\0\1\54\1\0\1\6"+
    "\1\0\3\6\1\71\3\6\3\0\3\6\1\0\3\6"+
    "\6\0\3\6\1\72\1\73\2\6\1\0\3\6\4\0"+
    "\1\55\1\0\1\56\1\0\1\57\7\0\1\6\1\54"+
    "\1\0\1\54\1\0\1\6\1\0\3\6\1\74\3\6"+
    "\3\0\3\6\1\0\3\6\6\0\3\6\1\75\3\6"+
    "\1\0\3\6\4\0\1\55\1\0\1\56\1\0\1\57"+
    "\7\0\1\6\1\54\1\0\1\54\1\0\1\6\1\0"+
    "\4\6\1\76\2\6\3\0\3\6\1\0\3\6\6\0"+
    "\3\6\1\0\3\6\1\0\3\6\4\0\1\55\1\0"+
    "\1\56\1\0\1\57\7\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\77\1\0\7\6\3\0\3\6\1\0\2\6"+
    "\1\77\6\0\3\6\1\0\3\6\1\0\3\6\4\0"+
    "\1\55\1\0\1\56\1\0\1\57\7\0\1\6\1\54"+
    "\1\0\1\54\1\0\1\6\1\0\7\6\3\0\3\6"+
    "\1\0\3\6\6\0\1\100\2\6\1\0\3\6\1\0"+
    "\3\6\4\0\1\55\1\0\1\56\1\0\1\57\7\0"+
    "\1\6\1\54\1\0\1\54\1\0\1\6\1\0\3\6"+
    "\1\16\3\6\3\0\3\6\1\0\3\6\6\0\3\6"+
    "\1\0\3\6\1\0\3\6\4\0\1\55\1\0\1\56"+
    "\1\0\1\57\25\0\1\22\1\101\67\0\2\22\1\101"+
    "\50\0\1\6\1\54\1\0\1\54\1\0\1\6\1\0"+
    "\7\6\3\0\1\6\1\102\1\6\1\0\3\6\6\0"+
    "\1\103\2\6\1\0\3\6\1\0\3\6\4\0\1\55"+
    "\1\0\1\56\1\0\1\57\7\0\1\6\1\54\1\0"+
    "\1\54\1\0\1\6\1\0\1\104\6\6\3\0\3\6"+
    "\1\0\3\6\6\0\3\6\1\0\3\6\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\7\0\1\60"+
    "\1\105\1\0\1\105\1\0\1\60\1\0\7\60\3\0"+
    "\3\60\1\0\3\60\1\62\1\106\1\0\1\62\2\0"+
    "\3\60\1\107\1\110\2\60\1\0\3\60\4\0\2\62"+
    "\1\63\1\0\1\64\1\0\1\65\5\0\1\60\1\105"+
    "\1\0\1\105\1\0\1\60\1\0\7\60\1\67\2\0"+
    "\3\60\1\0\3\60\2\62\1\0\1\62\2\0\3\60"+
    "\1\107\1\110\2\60\1\0\3\60\4\0\2\62\1\63"+
    "\1\0\1\64\1\0\1\65\5\0\1\60\1\105\1\0"+
    "\1\105\1\0\1\60\1\0\7\60\3\0\3\60\1\0"+
    "\3\60\2\62\1\0\1\62\2\0\3\60\1\107\1\110"+
    "\2\60\1\0\3\60\4\0\2\62\1\63\1\0\1\64"+
    "\1\0\1\65\37\32\1\22\31\32\23\0\1\67\16\0"+
    "\1\111\33\0\1\6\1\54\1\0\1\54\1\0\1\6"+
    "\1\0\7\6\3\0\3\6\1\0\3\6\6\0\3\6"+
    "\1\112\1\113\2\6\1\0\3\6\4\0\1\55\1\0"+
    "\1\56\1\0\1\57\7\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\6\1\0\3\6\1\114\3\6\3\0\3\6"+
    "\1\0\3\6\6\0\3\6\1\115\1\116\2\6\1\0"+
    "\3\6\4\0\1\55\1\0\1\56\1\0\1\57\17\0"+
    "\1\117\27\0\1\120\30\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\6\1\0\1\6\1\121\5\6\3\0\3\6"+
    "\1\0\3\6\6\0\2\6\1\122\1\0\3\6\1\0"+
    "\3\6\4\0\1\55\1\0\1\56\1\0\1\57\7\0"+
    "\1\6\1\54\1\0\1\54\1\0\1\6\1\0\3\6"+
    "\1\123\3\6\3\0\3\6\1\0\3\6\6\0\3\6"+
    "\1\0\3\6\1\0\3\6\4\0\1\55\1\0\1\56"+
    "\1\0\1\57\7\0\1\6\1\54\1\0\1\54\1\0"+
    "\1\6\1\0\1\124\6\6\3\0\3\6\1\0\3\6"+
    "\6\0\3\6\1\0\3\6\1\0\3\6\4\0\1\55"+
    "\1\0\1\56\1\0\1\57\14\0\1\125\21\0\1\125"+
    "\41\0\1\6\1\54\1\0\1\54\1\0\1\126\1\0"+
    "\7\6\3\0\3\6\1\0\2\6\1\126\6\0\3\6"+
    "\1\0\3\6\1\0\3\6\4\0\1\55\1\0\1\56"+
    "\1\0\1\57\25\0\1\67\70\0\1\67\35\0\1\127"+
    "\14\0\1\130\1\131\1\0\1\131\1\0\1\130\1\0"+
    "\7\130\3\0\3\130\1\0\3\130\2\62\1\0\1\62"+
    "\2\0\3\130\1\107\1\132\2\130\1\0\3\130\4\0"+
    "\1\133\1\62\1\134\1\0\1\135\1\0\1\65\5\0"+
    "\1\60\1\136\1\0\1\136\1\0\1\60\1\0\7\60"+
    "\3\0\3\60\1\0\3\60\2\62\1\0\1\62\2\0"+
    "\3\60\1\107\1\110\2\60\1\0\3\60\4\0\2\62"+
    "\1\63\1\0\1\64\1\0\1\65\65\0\1\47\1\0"+
    "\1\47\70\0\1\47\1\0\3\137\1\140\64\137\1\141"+
    "\5\0\2\54\1\0\1\54\1\0\1\54\1\0\7\54"+
    "\3\0\3\54\1\0\3\54\6\0\3\54\1\0\3\54"+
    "\1\0\3\54\20\0\2\130\1\0\1\130\1\0\1\130"+
    "\1\0\7\130\3\0\3\130\1\0\3\130\6\0\3\130"+
    "\1\0\3\130\1\0\3\130\4\0\1\55\1\0\1\56"+
    "\1\0\1\57\67\0\1\55\1\0\1\55\70\0\1\55"+
    "\6\0\1\60\4\0\1\60\1\0\7\60\3\0\3\60"+
    "\1\0\3\60\6\0\3\60\1\0\3\60\1\0\3\60"+
    "\21\0\1\142\1\0\1\142\1\0\1\143\63\0\1\60"+
    "\1\105\1\0\1\105\1\0\1\60\1\0\7\60\3\0"+
    "\3\60\1\0\3\60\2\62\1\0\1\62\2\0\3\60"+
    "\1\0\3\60\1\0\3\60\4\0\2\62\1\63\1\0"+
    "\1\64\1\0\1\65\65\0\1\62\1\0\1\62\70\0"+
    "\1\62\1\0\70\65\1\62\6\0\1\66\1\0\1\66"+
    "\1\0\1\143\63\0\1\6\1\54\1\0\1\54\1\0"+
    "\1\6\1\0\2\6\1\76\4\6\3\0\3\6\1\0"+
    "\3\6\6\0\3\6\1\0\3\6\1\0\3\6\4\0"+
    "\1\55\1\0\1\56\1\0\1\57\7\0\1\6\1\54"+
    "\1\0\1\54\1\0\1\6\1\0\5\6\1\76\1\6"+
    "\3\0\3\6\1\0\3\6\6\0\3\6\1\0\3\6"+
    "\1\0\3\6\4\0\1\55\1\0\1\56\1\0\1\57"+
    "\31\0\1\120\46\0\1\6\1\54\1\0\1\54\1\0"+
    "\1\6\1\0\7\6\3\0\1\6\1\122\1\6\1\0"+
    "\3\6\6\0\3\6\1\0\3\6\1\0\3\6\4\0"+
    "\1\55\1\0\1\56\1\0\1\57\7\0\1\6\1\54"+
    "\1\0\1\54\1\0\1\6\1\0\7\6\3\0\3\6"+
    "\1\0\3\6\6\0\1\6\1\144\1\6\1\0\3\6"+
    "\1\0\3\6\4\0\1\55\1\0\1\56\1\0\1\57"+
    "\57\0\1\67\20\0\1\6\1\54\1\0\1\54\1\0"+
    "\1\6\1\0\1\73\6\6\3\0\2\6\1\145\1\0"+
    "\3\6\6\0\3\6\1\0\2\6\1\146\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\7\0\1\6"+
    "\1\54\1\0\1\54\1\0\1\6\1\0\7\6\3\0"+
    "\3\6\1\0\3\6\6\0\3\6\1\0\2\6\1\147"+
    "\1\0\3\6\4\0\1\55\1\0\1\56\1\0\1\57"+
    "\25\0\1\44\52\0\1\6\1\54\1\0\1\54\1\0"+
    "\1\6\1\0\3\6\1\150\3\6\3\0\3\6\1\0"+
    "\3\6\6\0\3\6\1\0\3\6\1\0\3\6\4\0"+
    "\1\55\1\0\1\56\1\0\1\57\7\0\1\6\1\54"+
    "\1\0\1\54\1\0\1\6\1\0\5\6\1\147\1\6"+
    "\3\0\3\6\1\0\3\6\6\0\3\6\1\0\3\6"+
    "\1\0\3\6\4\0\1\55\1\0\1\56\1\0\1\57"+
    "\7\0\1\6\1\54\1\0\1\54\1\0\1\6\1\0"+
    "\7\6\3\0\1\151\2\6\1\0\3\6\6\0\3\6"+
    "\1\0\3\6\1\0\3\6\4\0\1\55\1\0\1\56"+
    "\1\0\1\57\7\0\1\60\1\105\1\0\1\105\1\152"+
    "\1\60\1\0\7\60\3\0\3\60\1\0\3\60\2\62"+
    "\1\0\1\62\2\0\3\60\1\0\3\60\1\0\3\60"+
    "\4\0\2\62\1\63\1\0\1\64\1\0\1\65\6\153"+
    "\1\154\1\153\1\154\24\153\1\106\1\62\1\153\1\62"+
    "\21\153\2\106\1\155\1\153\1\156\1\153\1\157\16\0"+
    "\1\160\57\0\1\60\4\0\1\60\1\0\2\60\1\161"+
    "\4\60\3\0\3\60\1\0\3\60\6\0\3\60\1\0"+
    "\3\60\1\0\3\60\13\0\2\111\2\0\3\111\1\0"+
    "\61\111\21\0\1\162\54\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\6\1\0\5\6\1\163\1\6\3\0\3\6"+
    "\1\0\3\6\6\0\3\6\1\0\3\6\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\7\0\1\6"+
    "\1\54\1\0\1\54\1\0\1\6\1\0\4\6\1\164"+
    "\2\6\3\0\3\6\1\0\3\6\6\0\3\6\1\0"+
    "\3\6\1\0\3\6\4\0\1\55\1\0\1\56\1\0"+
    "\1\57\31\0\1\165\46\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\6\1\0\7\6\3\0\1\6\1\147\1\6"+
    "\1\0\3\6\6\0\3\6\1\0\3\6\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\31\0\1\166"+
    "\46\0\1\6\1\54\1\0\1\54\1\0\1\6\1\0"+
    "\7\6\3\0\1\6\1\167\1\6\1\0\3\6\6\0"+
    "\3\6\1\0\3\6\1\0\3\6\4\0\1\55\1\0"+
    "\1\56\1\0\1\57\7\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\6\1\0\5\6\1\170\1\6\3\0\3\6"+
    "\1\0\3\6\6\0\3\6\1\0\3\6\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\7\0\1\6"+
    "\1\54\1\0\1\54\1\0\1\6\1\0\7\6\3\0"+
    "\2\6\1\171\1\0\3\6\6\0\3\6\1\0\3\6"+
    "\1\0\3\6\4\0\1\55\1\0\1\56\1\0\1\57"+
    "\23\0\1\120\54\0\1\6\1\54\1\0\1\54\1\0"+
    "\1\6\1\0\5\6\1\122\1\6\3\0\3\6\1\0"+
    "\3\6\6\0\3\6\1\0\3\6\1\0\3\6\4\0"+
    "\1\55\1\0\1\56\1\0\1\57\63\0\1\127\14\0"+
    "\2\130\1\0\1\130\1\0\1\130\1\0\7\130\3\0"+
    "\3\130\1\0\3\130\6\0\3\130\1\0\3\130\1\0"+
    "\3\130\20\0\1\130\1\131\1\0\1\131\1\152\1\130"+
    "\1\0\7\130\3\0\3\130\1\0\3\130\2\62\1\0"+
    "\1\62\2\0\3\130\1\0\3\130\1\0\3\130\4\0"+
    "\2\62\1\63\1\0\1\64\1\0\1\65\5\0\2\130"+
    "\1\0\1\130\1\0\1\130\1\0\2\130\1\172\4\130"+
    "\3\0\3\130\1\0\3\130\6\0\3\130\1\0\3\130"+
    "\1\0\3\130\20\0\1\130\1\131\1\0\1\131\1\0"+
    "\1\130\1\0\7\130\3\0\3\130\1\0\3\130\2\62"+
    "\1\0\1\62\2\0\3\130\1\0\3\130\1\0\3\130"+
    "\4\0\1\133\1\62\1\134\1\0\1\135\1\0\1\65"+
    "\65\0\1\133\1\0\1\133\70\0\1\133\6\0\1\60"+
    "\1\136\1\0\1\136\1\152\1\60\1\0\7\60\3\0"+
    "\3\60\1\0\3\60\2\62\1\0\1\62\2\0\3\60"+
    "\1\0\3\60\1\0\3\60\4\0\2\62\1\63\1\0"+
    "\1\64\1\0\1\65\70\173\1\174\2\173\1\137\65\173"+
    "\1\174\5\0\1\60\1\175\1\0\1\175\1\0\1\176"+
    "\1\0\7\60\3\0\3\60\1\0\3\60\2\62\1\0"+
    "\1\62\2\0\3\60\1\0\3\60\1\0\3\60\4\0"+
    "\2\62\1\63\1\0\1\64\1\0\1\65\1\0\1\177"+
    "\4\0\1\200\1\0\1\200\2\0\1\177\45\0\1\177"+
    "\14\0\1\6\1\54\1\0\1\54\1\0\1\6\1\0"+
    "\1\6\1\123\5\6\3\0\3\6\1\0\3\6\6\0"+
    "\3\6\1\0\3\6\1\0\3\6\4\0\1\55\1\0"+
    "\1\56\1\0\1\57\7\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\6\1\0\3\6\1\201\3\6\3\0\3\6"+
    "\1\0\3\6\6\0\3\6\1\0\3\6\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\7\0\1\6"+
    "\1\54\1\0\1\54\1\0\1\202\1\0\7\6\3\0"+
    "\3\6\1\0\2\6\1\202\6\0\3\6\1\0\3\6"+
    "\1\0\3\6\4\0\1\55\1\0\1\56\1\0\1\57"+
    "\7\0\1\6\1\54\1\0\1\54\1\0\1\122\1\0"+
    "\7\6\3\0\3\6\1\0\2\6\1\122\6\0\3\6"+
    "\1\0\3\6\1\0\3\6\4\0\1\55\1\0\1\56"+
    "\1\0\1\57\7\0\1\6\1\54\1\0\1\54\1\0"+
    "\1\6\1\0\7\6\3\0\2\6\1\203\1\0\3\6"+
    "\6\0\3\6\1\0\3\6\1\0\3\6\4\0\1\55"+
    "\1\0\1\56\1\0\1\57\7\0\1\6\1\54\1\0"+
    "\1\54\1\0\1\73\1\0\7\6\3\0\3\6\1\0"+
    "\2\6\1\73\6\0\3\6\1\0\3\6\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\10\0\1\204"+
    "\1\0\1\204\60\0\36\153\1\0\1\153\1\0\36\153"+
    "\1\154\1\153\1\154\1\205\23\153\1\106\1\62\1\153"+
    "\1\62\21\153\2\106\1\155\1\153\1\156\1\153\1\157"+
    "\36\153\1\0\1\153\1\0\24\153\1\106\1\153\1\106"+
    "\37\153\1\0\1\153\1\0\26\153\1\106\1\153\36\157"+
    "\1\65\1\157\1\65\27\157\1\106\12\0\1\206\21\0"+
    "\1\206\41\0\1\60\4\0\1\207\1\0\7\60\3\0"+
    "\3\60\1\0\2\60\1\207\6\0\3\60\1\0\3\60"+
    "\1\0\3\60\67\0\1\120\21\0\1\6\1\54\1\0"+
    "\1\54\1\0\1\6\1\0\7\6\3\0\3\6\1\0"+
    "\3\6\6\0\3\6\1\0\3\6\1\0\1\6\1\122"+
    "\1\6\4\0\1\55\1\0\1\56\1\0\1\57\7\0"+
    "\1\6\1\54\1\0\1\54\1\0\1\6\1\0\7\6"+
    "\3\0\3\6\1\0\3\6\6\0\1\6\1\210\1\6"+
    "\1\0\3\6\1\0\3\6\4\0\1\55\1\0\1\56"+
    "\1\0\1\57\14\0\1\120\21\0\1\120\102\0\2\211"+
    "\26\0\1\6\1\54\1\0\1\54\1\0\1\6\1\0"+
    "\7\6\3\0\3\6\1\0\3\6\6\0\3\6\1\211"+
    "\1\212\2\6\1\0\3\6\4\0\1\55\1\0\1\56"+
    "\1\0\1\57\7\0\1\6\1\54\1\0\1\54\1\0"+
    "\1\6\1\0\3\6\1\122\3\6\3\0\3\6\1\0"+
    "\3\6\6\0\3\6\1\0\3\6\1\0\3\6\4\0"+
    "\1\55\1\0\1\56\1\0\1\57\7\0\1\6\1\54"+
    "\1\0\1\54\1\0\1\6\1\0\7\6\3\0\3\6"+
    "\1\213\1\214\2\6\6\0\3\6\1\0\3\6\1\0"+
    "\3\6\4\0\1\55\1\0\1\56\1\0\1\57\7\0"+
    "\2\130\1\0\1\130\1\0\1\215\1\0\7\130\3\0"+
    "\3\130\1\0\2\130\1\215\6\0\3\130\1\0\3\130"+
    "\1\0\3\130\13\0\70\173\1\141\5\0\1\60\1\175"+
    "\1\0\1\175\1\152\1\176\1\0\7\60\3\0\3\60"+
    "\1\0\3\60\2\62\1\0\1\62\2\0\3\60\1\0"+
    "\3\60\1\0\3\60\4\0\2\62\1\63\1\0\1\64"+
    "\1\0\1\65\1\0\1\216\3\0\1\60\1\217\1\0"+
    "\1\217\1\0\1\60\1\216\7\60\3\0\3\60\1\0"+
    "\3\60\6\0\3\60\1\0\3\60\1\0\3\60\3\0"+
    "\1\216\15\0\1\200\1\0\1\200\65\0\1\6\1\54"+
    "\1\0\1\54\1\0\1\6\1\0\4\6\1\220\2\6"+
    "\3\0\3\6\1\0\3\6\6\0\3\6\1\0\3\6"+
    "\1\0\3\6\4\0\1\55\1\0\1\56\1\0\1\57"+
    "\7\0\1\6\1\54\1\0\1\54\1\0\1\6\1\0"+
    "\1\126\6\6\3\0\3\6\1\0\3\6\6\0\3\6"+
    "\1\0\3\6\1\0\3\6\4\0\1\55\1\0\1\56"+
    "\1\0\1\57\7\0\1\6\1\54\1\0\1\54\1\0"+
    "\1\6\1\0\7\6\3\0\3\6\1\221\1\222\2\6"+
    "\6\0\3\6\1\0\3\6\1\0\3\6\4\0\1\55"+
    "\1\0\1\56\1\0\1\57\7\0\1\60\1\223\1\0"+
    "\1\223\1\0\1\224\1\0\7\60\3\0\3\60\1\0"+
    "\3\60\2\62\1\0\1\62\2\0\3\60\1\0\3\60"+
    "\1\0\3\60\4\0\2\62\1\63\1\0\1\64\1\0"+
    "\1\65\6\153\1\225\1\153\1\225\25\153\1\0\1\153"+
    "\1\0\30\153\15\0\1\226\60\0\1\60\4\0\1\60"+
    "\1\0\1\60\1\227\5\60\3\0\3\60\1\0\3\60"+
    "\6\0\3\60\1\0\3\60\1\0\3\60\20\0\1\6"+
    "\1\54\1\0\1\54\1\0\1\6\1\0\1\201\6\6"+
    "\3\0\3\6\1\0\3\6\6\0\3\6\1\0\3\6"+
    "\1\0\3\6\4\0\1\55\1\0\1\56\1\0\1\57"+
    "\17\0\1\165\60\0\1\6\1\54\1\0\1\54\1\0"+
    "\1\6\1\0\1\6\1\147\5\6\3\0\3\6\1\0"+
    "\3\6\6\0\3\6\1\0\3\6\1\0\3\6\4\0"+
    "\1\55\1\0\1\56\1\0\1\57\14\0\1\230\21\0"+
    "\1\230\41\0\1\6\1\54\1\0\1\54\1\0\1\220"+
    "\1\0\7\6\3\0\3\6\1\0\2\6\1\220\6\0"+
    "\3\6\1\0\3\6\1\0\3\6\4\0\1\55\1\0"+
    "\1\56\1\0\1\57\7\0\2\130\1\0\1\130\1\0"+
    "\1\130\1\0\1\130\1\231\5\130\3\0\3\130\1\0"+
    "\3\130\6\0\3\130\1\0\3\130\1\0\3\130\21\0"+
    "\1\232\1\0\1\232\65\0\1\60\1\233\1\0\1\233"+
    "\1\234\1\235\1\0\7\60\3\0\3\60\1\0\3\60"+
    "\2\62\1\0\1\62\2\0\3\60\1\0\3\60\1\0"+
    "\3\60\4\0\2\62\1\63\1\0\1\64\1\0\1\65"+
    "\5\0\1\6\1\54\1\0\1\54\1\0\1\6\1\0"+
    "\2\6\1\122\4\6\3\0\3\6\1\0\3\6\6\0"+
    "\3\6\1\0\3\6\1\0\3\6\4\0\1\55\1\0"+
    "\1\56\1\0\1\57\32\0\1\236\45\0\1\6\1\54"+
    "\1\0\1\54\1\0\1\6\1\0\7\6\3\0\2\6"+
    "\1\237\1\0\3\6\6\0\3\6\1\0\3\6\1\0"+
    "\3\6\4\0\1\55\1\0\1\56\1\0\1\57\7\0"+
    "\1\60\1\223\1\0\1\223\1\152\1\224\1\0\7\60"+
    "\3\0\3\60\1\0\3\60\2\62\1\0\1\62\2\0"+
    "\3\60\1\0\3\60\1\0\3\60\4\0\2\62\1\63"+
    "\1\0\1\64\1\0\1\65\1\0\1\240\3\0\1\60"+
    "\1\241\1\0\1\241\1\0\1\60\1\240\7\60\3\0"+
    "\3\60\1\0\3\60\6\0\3\60\1\0\3\60\1\0"+
    "\3\60\3\0\1\240\7\0\6\153\1\242\1\153\1\242"+
    "\1\153\1\243\22\153\1\106\1\62\1\153\1\62\21\153"+
    "\2\106\1\155\1\153\1\156\1\153\1\157\45\0\1\244"+
    "\30\0\1\60\4\0\1\60\1\0\7\60\3\0\3\60"+
    "\1\0\3\60\6\0\2\60\1\245\1\0\3\60\1\0"+
    "\3\60\31\0\1\120\57\0\2\130\1\0\1\130\1\0"+
    "\1\130\1\0\7\130\3\0\3\130\1\0\3\130\6\0"+
    "\2\130\1\246\1\0\3\130\1\0\3\130\20\0\1\60"+
    "\1\233\1\0\1\233\1\0\1\235\1\0\7\60\3\0"+
    "\3\60\1\0\3\60\2\62\1\0\1\62\2\0\3\60"+
    "\1\0\3\60\1\0\3\60\4\0\2\62\1\63\1\0"+
    "\1\64\1\0\1\65\5\0\1\60\1\233\1\0\1\233"+
    "\1\152\1\235\1\0\7\60\3\0\3\60\1\0\3\60"+
    "\2\62\1\0\1\62\2\0\3\60\1\0\3\60\1\0"+
    "\3\60\4\0\2\62\1\63\1\0\1\64\1\0\1\65"+
    "\41\0\1\247\30\0\1\250\3\0\1\60\1\251\1\0"+
    "\1\251\1\0\1\60\1\250\7\60\3\0\3\60\1\0"+
    "\3\60\6\0\3\60\1\0\3\60\1\0\3\60\3\0"+
    "\1\250\26\0\1\252\56\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\6\1\0\3\6\1\253\3\6\3\0\3\6"+
    "\1\0\3\6\6\0\3\6\1\0\3\6\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\10\0\1\241"+
    "\1\0\1\241\65\0\1\60\1\254\1\0\1\254\1\0"+
    "\1\255\1\0\7\60\3\0\3\60\1\0\3\60\2\62"+
    "\1\0\1\62\2\0\3\60\1\0\3\60\1\0\3\60"+
    "\4\0\2\62\1\63\1\0\1\64\1\0\1\65\6\153"+
    "\1\242\1\153\1\242\1\205\1\243\22\153\1\106\1\62"+
    "\1\153\1\62\21\153\2\106\1\155\1\153\1\156\1\153"+
    "\1\157\1\153\1\256\4\153\1\257\1\153\1\257\2\153"+
    "\1\256\22\153\1\0\1\153\1\0\20\153\1\256\7\153"+
    "\46\0\2\260\26\0\1\60\4\0\1\60\1\0\7\60"+
    "\3\0\3\60\1\0\3\60\6\0\3\60\1\260\1\261"+
    "\2\60\1\0\3\60\20\0\2\130\1\0\1\130\1\0"+
    "\1\130\1\0\7\130\3\0\3\130\1\0\3\130\6\0"+
    "\3\130\1\260\1\262\2\130\1\0\3\130\31\0\1\263"+
    "\60\0\1\264\1\0\1\264\65\0\1\60\1\265\1\0"+
    "\1\265\1\234\1\60\1\0\7\60\3\0\3\60\1\0"+
    "\3\60\2\62\1\0\1\62\2\0\3\60\1\0\3\60"+
    "\1\0\3\60\4\0\2\62\1\63\1\0\1\64\1\0"+
    "\1\65\33\0\1\266\42\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\6\1\0\7\6\3\0\3\6\1\0\1\6"+
    "\1\267\1\6\6\0\3\6\1\0\3\6\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\7\0\1\60"+
    "\1\254\1\0\1\254\1\152\1\255\1\0\7\60\3\0"+
    "\3\60\1\0\3\60\2\62\1\0\1\62\2\0\3\60"+
    "\1\0\3\60\1\0\3\60\4\0\2\62\1\63\1\0"+
    "\1\64\1\0\1\65\1\0\1\270\3\0\1\60\1\62"+
    "\1\0\1\62\1\0\1\60\1\270\7\60\3\0\3\60"+
    "\1\0\3\60\6\0\3\60\1\0\3\60\1\0\3\60"+
    "\3\0\1\270\7\0\6\153\1\257\1\153\1\257\25\153"+
    "\1\0\1\153\1\0\36\153\1\271\1\153\1\271\1\153"+
    "\1\272\22\153\1\106\1\62\1\153\1\62\21\153\2\106"+
    "\1\155\1\153\1\156\1\153\1\157\21\0\1\273\54\0"+
    "\1\60\4\0\1\60\1\0\5\60\1\274\1\60\3\0"+
    "\3\60\1\0\3\60\6\0\3\60\1\0\3\60\1\0"+
    "\3\60\20\0\2\130\1\0\1\130\1\0\1\130\1\0"+
    "\5\130\1\275\1\130\3\0\3\130\1\0\3\130\6\0"+
    "\3\130\1\0\3\130\1\0\3\130\61\0\2\276\26\0"+
    "\1\60\1\265\1\0\1\265\1\0\1\60\1\0\7\60"+
    "\3\0\3\60\1\0\3\60\2\62\1\0\1\62\2\0"+
    "\3\60\1\0\3\60\1\0\3\60\4\0\2\62\1\63"+
    "\1\0\1\64\1\0\1\65\5\0\1\60\1\265\1\0"+
    "\1\265\1\152\1\60\1\0\7\60\3\0\3\60\1\0"+
    "\3\60\2\62\1\0\1\62\2\0\3\60\1\0\3\60"+
    "\1\0\3\60\4\0\2\62\1\63\1\0\1\64\1\0"+
    "\1\65\33\0\1\277\42\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\6\1\0\7\6\3\0\3\6\1\0\1\6"+
    "\1\300\1\6\6\0\3\6\1\0\3\6\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\10\0\1\62"+
    "\1\0\1\62\60\0\6\153\1\271\1\153\1\271\1\205"+
    "\1\272\22\153\1\106\1\62\1\153\1\62\21\153\2\106"+
    "\1\155\1\153\1\156\1\153\1\157\1\153\1\301\4\153"+
    "\1\106\1\153\1\106\2\153\1\301\22\153\1\0\1\153"+
    "\1\0\20\153\1\301\7\153\46\0\2\302\26\0\1\60"+
    "\4\0\1\60\1\0\7\60\3\0\3\60\1\0\3\60"+
    "\6\0\3\60\1\302\3\60\1\0\3\60\20\0\2\130"+
    "\1\0\1\130\1\0\1\130\1\0\7\130\3\0\3\130"+
    "\1\0\3\130\6\0\3\130\1\302\3\130\1\0\3\130"+
    "\63\0\1\303\32\0\1\304\21\0\1\304\41\0\1\6"+
    "\1\54\1\0\1\54\1\0\1\305\1\0\7\6\3\0"+
    "\3\6\1\0\2\6\1\305\6\0\3\6\1\0\3\6"+
    "\1\0\3\6\4\0\1\55\1\0\1\56\1\0\1\57"+
    "\2\0\6\153\1\106\1\153\1\106\25\153\1\0\1\153"+
    "\1\0\30\153\45\0\1\306\71\0\2\307\36\0\1\310"+
    "\60\0\1\6\1\54\1\0\1\54\1\0\1\6\1\0"+
    "\1\6\1\311\5\6\3\0\3\6\1\0\3\6\6\0"+
    "\3\6\1\0\3\6\1\0\3\6\4\0\1\55\1\0"+
    "\1\56\1\0\1\57\14\0\1\312\21\0\1\312\55\0"+
    "\1\313\70\0\1\314\54\0\1\6\1\54\1\0\1\54"+
    "\1\0\1\6\1\0\5\6\1\315\1\6\3\0\3\6"+
    "\1\0\3\6\6\0\3\6\1\0\3\6\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\22\0\1\316"+
    "\107\0\1\317\54\0\1\320\52\0\1\6\1\54\1\0"+
    "\1\54\1\0\1\6\1\0\7\6\1\320\2\0\3\6"+
    "\1\0\3\6\6\0\3\6\1\0\3\6\1\0\3\6"+
    "\4\0\1\55\1\0\1\56\1\0\1\57\61\0\1\321"+
    "\46\0\1\322\71\0\1\323\32\0\36\323\1\324\1\0"+
    "\67\323\1\324\1\0\1\325\30\323";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11400];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\1\1\1\11\15\1\1\11\21\1\1\11"+
    "\11\1\2\0\2\1\4\0\1\1\1\11\2\1\1\0"+
    "\2\1\1\0\7\1\1\0\1\1\1\0\2\1\1\0"+
    "\2\1\1\0\2\1\1\11\4\1\1\0\6\1\2\0"+
    "\5\1\1\0\6\1\1\0\5\1\1\0\1\1\1\0"+
    "\2\1\2\0\10\1\1\0\4\1\1\0\1\1\1\0"+
    "\2\1\1\0\1\1\1\0\2\1\1\0\2\1\1\0"+
    "\1\1\1\0\2\1\1\0\1\1\1\0\3\1\1\0"+
    "\1\1\1\0\1\1\2\0\2\1\1\0\2\1\2\0"+
    "\1\1\1\0\1\1\1\0\3\1\1\0\2\1\1\0"+
    "\2\1\1\0\1\1\1\0\2\1\1\0\2\1\2\0"+
    "\2\1\3\0\1\1\3\0\1\1\3\0\1\1\1\11"+
    "\2\0\1\11\3\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
 
 /* C�digo personalizado */
 
 // Se agreg� una propiedad para verificar si existen tokens pendientes
 private boolean _existenTokens = false;
 
 public boolean existenTokens(){
 return this._existenTokens;
 }

private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
}

private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
}

private Symbol symbol(String value, int type, int line) {
    return new Symbol(type, yyline, yycolumn, (Object)value);
}
 


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScannerABC(java.io.Reader in) {
   /* C�digo que se ejecutar� en el constructor de la clase */
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 270) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
     
 /* C�digo a ejecutar al finalizar el an�lisis, en este caso cambiaremos el valor de una variable bandera */
 this._existenTokens = false;
 

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { //Espacios y tabuladores
            }
          case 24: break;
          case 2: 
            { Symbol t = new Symbol(sym.ERROR_INVALID_CHARACTER, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.ERROR_INVALID_CHARACTER, yyline);
    this._existenTokens = true;
    return t;
            }
          case 25: break;
          case 3: 
            { /*Token t = new Token("Enter", Types.IDENTIFIER);
 this._existenTokens = true;
 return t;*/
            }
          case 26: break;
          case 4: 
            { Symbol t = new Symbol(sym.IDENTIFIER, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.IDENTIFIER, yyline);
    if (yytext().length()>127){
        t = new Symbol(sym.ERROR_INVALID_LENGTH, yyline, yycolumn, (Object)yytext());
        //t.setType(Types.ERROR_INVALID_LENGTH);
    }
     this._existenTokens = true;
     return t;
            }
          case 27: break;
          case 5: 
            { Symbol t = new Symbol(sym.INTEGER_NUMERIC_LITERAL, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.INTEGER_NUMERIC_LITERAL, yyline);
    this._existenTokens = true;
    return t;
            }
          case 28: break;
          case 6: 
            { Symbol t = new Symbol(sym.ERROR_INTEGER, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.ERROR_INTEGER, yyline);
    this._existenTokens = true;
    return t;
            }
          case 29: break;
          case 7: 
            { Symbol t = new Symbol(sym.OPERATOR, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.OPERATOR, yyline);
    this._existenTokens = true;
    return t;
            }
          case 30: break;
          case 8: 
            { Symbol t = new Symbol(sym.ARITHMETICOP, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.ARITHMETICOP, yyline);
    this._existenTokens = true;
    return t;
            }
          case 31: break;
          case 9: 
            { Symbol t = new Symbol(sym.BOOLEAN_OPERATOR, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.BOOLEAN_OPERATOR, yyline);
    this._existenTokens = true;
    return t;
            }
          case 32: break;
          case 10: 
            { Symbol t = new Symbol(sym.OPEN_PARENTHESIS, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.OPEN_PARENTHESIS, yyline);
    this._existenTokens = true;
    return t;
            }
          case 33: break;
          case 11: 
            { Symbol t = new Symbol(sym.CLOSE_PARENTHESIS, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.CLOSE_PARENTHESIS, yyline);
    this._existenTokens = true;
    return t;
            }
          case 34: break;
          case 12: 
            { Symbol t = new Symbol(sym.ERROR_COMMENT, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.ERROR_COMMENT, yyline);
    this._existenTokens = true;
    return t;
    //return symbol(sym.ERROR_COMMENT);
            }
          case 35: break;
          case 13: 
            { //Token t = new Token(yytext(), Types.ERROR_INVALID_CHARACTER, yyline);
    Symbol t = new Symbol(sym.ERROR_INVALID_CHARACTER, yyline, yycolumn, (Object)yytext());
    this._existenTokens = true;
    //return new Symbol(sym.ERROR_INVALID_CHARACTER);
    return t;
            }
          case 36: break;
          case 14: 
            { Symbol t = new Symbol(sym.ERROR_STRING, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.ERROR_STRING, yyline);
    this._existenTokens = true;
    return t;
            }
          case 37: break;
          case 15: 
            { Symbol t = new Symbol(sym.ERROR_IDENTIFIER, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.ERROR_IDENTIFIER, yyline);
    this._existenTokens = true;
    //return symbol(sym.ERROR_IDENTIFIER);
    return t;
            }
          case 38: break;
          case 16: 
            { Symbol t = new Symbol(sym.ERROR_FLOATING_POINT, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.ERROR_FLOATING_POINT, yyline);
    this._existenTokens = true;
    return t;
            }
          case 39: break;
          case 17: 
            { // Comentario de bloque 1
            }
          case 40: break;
          case 18: 
            { Symbol t = new Symbol(sym.RESERVED, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.RESERVED, yyline);
    this._existenTokens = true;
    return t;
            }
          case 41: break;
          case 19: 
            { Symbol t = new Symbol(sym.NUMERIC_CHAR_LITERAL, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.NUMERIC_CHAR_LITERAL, yyline);
    this._existenTokens = true;
    return t;
            }
          case 42: break;
          case 20: 
            { Symbol t = new Symbol(sym.STRING_LITERAL, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.STRING_LITERAL, yyline);
    this._existenTokens = true;
    return t;
            }
          case 43: break;
          case 21: 
            { Symbol t = new Symbol(sym.IDENTIFIER, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.FLOATING_POINT_NUMERIC_LITERAL, yyline);
    this._existenTokens = true;
    return t;
            }
          case 44: break;
          case 22: 
            { Symbol t = new Symbol(sym.CHAR_LITERAL, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.CHAR_LITERAL, yyline);
    this._existenTokens = true;
    return t;
            }
          case 45: break;
          case 23: 
            { Symbol t = new Symbol(sym.SCIENTIFIC_NOTATION_NUMERIC_LITERAL, yyline, yycolumn, (Object)yytext());
    //Token t = new Token(yytext(), Types.SCIENTIFIC_NOTATION_NUMERIC_LITERAL, yyline);
    this._existenTokens = true;
    return t;
            }
          case 46: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
